# Generated by Django 4.0.3 on 2022-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorschedule',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
