# Generated by Django 4.0.3 on 2022-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_schedule', '0002_mentorschedule_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
