# Generated by Django 4.0.3 on 2022-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_schedule', '0003_alter_mentorschedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorschedule',
            name='exDate',
            field=models.TextField(null=True),
        ),
    ]
